flowchart LR
    id1(This is the text in the box)
    id2([This is the text in the squircle])
    id3[[This is the text in the subroutine box]]
    id4[(Database)]
    id5((This is the text in the circle))
    id6>This is the text in the asymmetric  box]
    id7{This is the text in the rhombus}
    id8{{This is the text in the hexagon}}
    id9[/This is the text in the parallelogram/]
    id10[\This is the text in the alt parallelogram\]
    id11[/Trapezoid\]
    id12[\Alt Trapezoid/]
    id13(((This is the text in the double circle)))
