flowchart LR
    a1-->a2
    b1 --- b2
    c1-- text ---c2
    d1---|text|d2
    e1-->|text|e2
    f1--text-->f2
    g1-.-g2
    h1-. text .-> h2
    i1 ==> i2
    j1 == text ==> j2
    k1 ~~~ k2
    l1 -- text --> l2 -- text --> l3
    m1 --> m2 & m3 --> m4
    n1 & n2 --> n3 & n4
    o1 e1@--> o2
