sequenceDiagram
    box Aqua Group of actors
        participant Alice
        participant Bob
    end
    box rgb(33,66,99) Another group
        participant Charlie
    end
    Alice->>Bob: Hello
    Bob->>Charlie: Hi
