timeline
    title MermaidChart 2023 Timeline
    section Q1
        Makrdown : Updated Rendering : Pro diagrams : Recipe feature
    section Q2
        Desktop App : Commenting
    section Q3
        New diagram types : Plugin integration
    section Q4
        Code blocks : Review
